# To listen this TCP port on all interfaces, not only localhost
listener 1883

# OK for demo, but in prod - password_file and ACL
allow_anonymous true

# Keep retained messages between broker restarts
persistence true
persistence_location /mosquitto/data/

# Log to console of container: visible in "docker compose logs broker"
log_dest stdout
